### ISSUE TITLE
Smashes blocks together without whitespace

### ISSUE THREAD

**Issue by andersk** [syntax-tree/mdast-util-to-string#10]
### Initial checklist

- [X] I read the [support docs](https://github.com/syntax-tree/.github/blob/main/support.md)
- [X] I read the [contributing guide](https://github.com/syntax-tree/.github/blob/main/contributing.md)
- [X] I agree to follow the [code of conduct](https://github.com/syntax-tree/.github/blob/main/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Asyntax-tree&type=Issues) and couldn’t find anything (or linked relevant results below)

### Affected packages and versions

mdast-util-to-string@3.1.0

### Link to runnable example

https://codesandbox.io/s/priceless-sara-erpn8q

### Steps to reproduce

```js
import { fromMarkdown } from "mdast-util-from-markdown";
import { toString } from "mdast-util-to-string";

const tree = fromMarkdown(`
# heading

## heading

paragraph

   code

1. item
   - item
   - item
2. item

> blockquote
`);

console.log(toString(tree));
```

### Expected behavior

Blocks should be separated by whitespace in the output, perhaps something like

```
heading

heading

paragraph

code

item
item
item
item

blockquote
```

### Actual behavior

```
headingheadingparagraphcodeitemitemitemitemblockquote
```

### Affected runtime and version

node@18.12.1

**Comment by wooorm** [comment]
It is intended that this project is tiny. Knowledge of “blocks” vs “inlines” would be quite complex to get right, especially because you are not putting blank lines in your example between list items, or the paragraph (first `item`) and the following list. 

See the readme for more info on what this is and when to use it vs. alternatives: https://github.com/syntax-tree/mdast-util-to-string#when-should-i-use-this. I think you’re looking for `mdast-util-to-markdown`. Or you could make something to suit your specific needs on top of `mdast-util-to-string`
